apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apaas-architecture-control
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - configmaps
  - secrets
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - wasme.io
  resources:
  - filterdeployments
  verbs:
  - '*'
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  - filterdeployments
  verbs:
  - '*'